-- usuario
DROP TABLE IF EXISTS `usuario`;
CREATE TABLE IF NOT EXISTS `usuario` (
	`idusu` int(10) AUTO_INCREMENT NOT NULL COMMENT 'Identificador de usuario.',
	`idrol` varchar(3) NOT NULL COMMENT 'Identificador de rol de usuario.',
	`cedula` int(15) NOT NULL COMMENT 'Numero de cedula de identidad del usuario.',
	`nombre` varchar(50) NOT NULL COMMENT 'Nombres del usuario.',
	`apellido` varchar(50) NOT NULL COMMENT 'Apellidos del usuario.',
	`genero` varchar(15) NOT NULL COMMENT 'Genero del usuario.',
	`fecha_nacimiento` date NOT NULL COMMENT 'Fecha de nacimiento del usuario.',
	`nacionalidad` varchar(20) NOT NULL COMMENT 'Nacionalidad del usuario.',
	`direccion` varchar(50) NOT NULL COMMENT 'Dirección de residencia del usuario.',
	`telefono` varchar(15) NOT NULL COMMENT 'Teléfono de contacto.',
	`email` varchar(50) NOT NULL COMMENT 'Correo electrónico del usuario.',
	`user` varchar(15) NOT NULL COMMENT 'Nombre del usuario en la aplicación.',
	`pass` varchar(15) NOT NULL COMMENT 'Contraseña del usuario.',
	`fecha_registro` datetime NOT NULL COMMENT 'Fecha de creacion del registro.',
	`fecha_edicion` datetime NOT NULL COMMENT 'Fecha de ultima edicion del registro.',
	`estado_registro` int(1) NOT NULL COMMENT 'Codigo del estado del registro.',
	PRIMARY KEY (`idusu`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `usuario` (`idusu`,`idrol`,`cedula`,`nombre`,`apellido`,`genero`,`fecha_nacimiento`,`nacionalidad`,`direccion`,`telefono`,`email`,`user`,`pass`,`fecha_registro`,`fecha_edicion`,`estado_registro`) VALUES
(NULL, 'ADM', 99999999, 'Admin', 'SYS', 'Masculino', NOW(), 'Venezolano/a','Maracaibo', '0261-9999999', 'admin@sysrepo.com.ve', 'admin', 'admin', NOW(), NOW(), 1),
(NULL, 'USR', 99999999, 'Demo', 'SYS', 'Masculino', NOW(), 'Venezolano/a','Maracaibo', '0261-9999999', 'demo@sysrepo.com.ve', 'demo', 'demo', NOW(), NOW(), 1),
(NULL, 'USR', 99999999, 'Elina', 'Gonzalez', 'Femenino', NOW(), 'Venezolano/a','Maracaibo', '0261-9999999', 'elina@sysrepo.com.ve', 'elina', 'elina', NOW(), NOW(), 1),
(NULL, 'USR', 99999999, 'Luis', 'Oliva', 'Masculino', NOW(), 'Venezolano/a','Maracaibo', '0261-9999999', 'luis@sysrepo.com.ve', 'luis', 'luis', NOW(), NOW(), 1),
(NULL, 'USR', 99999999, 'Christopher', 'Mestre', 'Masculino', NOW(), 'Venezolano/a','Maracaibo', '0261-9999999', 'whispers@sysrepo.com', 'whispers', 'whispers', NOW(), NOW(), 1);

-- codigo
DROP TABLE IF EXISTS `codigo`;
CREATE TABLE IF NOT EXISTS `codigo` (
	`idcod` int(11) AUTO_INCREMENT NOT NULL COMMENT 'Identificador de codigo fuente.',
	`idcodori` int(11) NULL COMMENT 'Identificador de codigo fuente padre.',
	`idusu` int(11) NOT NULL COMMENT 'Identificador de usuario.',
	`titulo` varchar(100) NOT NULL COMMENT 'Titulo del codigo fuente.',
	`descripcion` varchar(100) NOT NULL COMMENT 'Descripcion del codigo fuente.',
	`lenguaje` varchar(15) NOT NULL COMMENT 'Lenguaje de programacion del codigo fuente.',
	`codigo` varchar(10000) NOT NULL COMMENT 'Codigo fuente.',
	`vistas` int(11) NOT NULL COMMENT 'Cantidad de vistas realizadas al codigo fuente.',
	`descargas` int(11) NOT NULL COMMENT 'Cantidad de descargas realizadas al codigo fuente.',
	`ejecuciones` int(11) NOT NULL COMMENT 'Cantidad de ejecuciones realizadas al codigo fuente.',
	`estado_codigo` int(1) NOT NULL COMMENT 'Codigo del estado de aprobacion del registro.',
	`fecha_registro` datetime NOT NULL COMMENT 'Fecha de creacion del registro.',
	`fecha_edicion` datetime NOT NULL COMMENT 'Fecha de ultima edicion del registro.',
	`estado_registro` int(1) NOT NULL COMMENT 'Codigo del estado del registro.',
	PRIMARY KEY (`idcod`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `codigo` (`idcod`,`idcodori`,`idusu`,`titulo`,`descripcion`,`lenguaje`,`codigo`,`vistas`,`descargas`,`ejecuciones`,`estado_codigo`,`fecha_registro`,`fecha_edicion`,`estado_registro`) VALUES 
(NULL, NULL, 1, 'Hola Mundo JS', 'Primer programa en JS', 'JavaScript', '<!DOCTYPE html>\r\n<html>\r\n    <head>\r\n        <title>Titulo de la pagina..</title>\r\n    </head>\r\n    <body>\r\n        <script type="text/javascript">\r\n            alert(''Hola Mundo!'');\r\n        </script>\r\n        Hola Mundo en Javascript\r\n    </body>\r\n</html>', 0, 0, 0, 0, NOW(), NOW(), 1),
(NULL, NULL, 1, 'Calculo dias vividos en JS', 'Programa en Javascript que calcula cuantos anios, meses y dias ha vivido una persona', 'JavaScript', '<!DOCTYPE html>\r\n<html>\r\n    <head>\r\n        <title>Titulo de la pagina..</title>\r\n        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>\r\n    </head>\r\n    <body>\r\n        <script type="text/javascript">\r\n            //MENSAJE DEL ADMIN: FAVOR CORREGIR LAS VARIABLES.\r\n            var diasVida = parseInt(prompt("Cuantos dAas has vivido",""));\r\n            var numAnos = Math.floor(diasVida / 365);\r\n            var diasRestantes = diasVida % 365 ;\r\n            var numMeses = Math.floor(diasRestantes / 30);\r\n            diasRestantes = diasRestantes % 30;\r\n            \r\n            alert("Ha vivido " + numAnos + " anios, " + numMeses + " meses y " + diasRestantes + " dAas.");\r\n        </script>\r\n    </body>\r\n</html>', 0, 0, 0, 0, NOW(), NOW(), 1),
(NULL, NULL, 1, 'Calcula distancia entre dos (2) puntos X Y', 'Formula para efecturar calculo de distancia AX, AY, BX y BY', 'JavaScript', '<!DOCTYPE html>\r\n<html>\r\n    <head>\r\n        <title>Titulo de la pagina..</title>\r\n        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>\r\n    </head>\r\n    <body>\r\n        <script type="text/javascript">\r\n            //ADMIN: explicar mejor la formula en comentarios.\r\n            var ax = prompt("Dame punto a coordenada x","");\r\n            var ay = prompt("Dame punto a coordenada y","");\r\n            var bx = prompt("Dame punto b coordenada x","");\r\n            var by = prompt("Dame punto b coordenada y","");\r\n            \r\n            var comp_horizontal = (bx-ax);\r\n            var comp_vertical = (by-ay);\r\n            comp_horizontal = comp_horizontal * comp_horizontal;\r\n            comp_vertical = comp_vertical * comp_vertical;\r\n            var distancia = Math.sqrt(comp_horizontal + comp_vertical);\r\n            \r\n            alert(distancia);\r\n        </script>\r\n    </body>\r\n</html>', 0, 0, 0, 0, NOW(), NOW(), 1),
(NULL, NULL, 1, 'Imprime variable texto', 'Programa que emite un mensaje de saludo con variable', 'JavaScript', '<!DOCTYPE html>\r\n<html>\r\n    <head>\r\n        <title>Programa3</title>\r\n        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>\r\n    </head>\r\n    <body>\r\n        <script type="text/javascript">\r\n            var nombre=prompt(''Escriba su nombre:'', '' '');\r\n            document.write(''Hola ''+nombre+'' ¿Como Estas?''); \r\n        </script>\r\n    </body>\r\n</html>', 0, 0, 0, 0, NOW(), NOW(), 1),
(NULL, NULL, 1, 'Cuenta numeros del 1 al 10', 'Imprime los numeros del 1 al 10 en JS', 'JavaScript', '<!DOCTYPE html>\r\n<html>\r\n    <head>\r\n        <title>Titulo de la pagina..</title>\r\n        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>\r\n    </head>\r\n    <body>\r\n        <script type="text/javascript">\r\n            for(var i=1;i<=10;i++){\r\n                //comentario de prueba\r\n                document.write(i);\r\n                document.write(''<br>'');\r\n            }\r\n        </script>\r\n    </body>\r\n</html>', 0, 0, 0, 0, NOW(), NOW(), 1),
(NULL, NULL, 2, 'Piramide de numeros', 'Genera numeros desde el 1 al 50', 'JavaScript', '<!DOCTYPE html>\r\n<html>\r\n    <head>\r\n        <title>Piramide de numeros</title>\r\n        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>\r\n    </head>\r\n    <body>\r\n        <script type="text/javascript">\r\n            var i,j;\r\n            for (i=1; i<=50; i++) {\r\n                for (j=1; j<=i; j++) {\r\n                    document.write(j);\r\n                }\r\n                document.write(''<br>'');\r\n            } \r\n        </script>\r\n    </body>\r\n</html>', 0, 0, 0, 0, NOW(), NOW(), 1),
(NULL, NULL, 2, 'prueba-demo', 'Pruebas de funcionamiento by demo', 'JavaScript', '<!DOCTYPE html>\r\n<html>\r\n    <head>\r\n        <title>Titulo de la pagina..</title>\r\n        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>\r\n    </head>\r\n    <body>\r\n        <script type="text/javascript">\r\n            alert(''Mensaje de prueba'');\r\n        </script>\r\n    </body>\r\n</html>', 0, 0, 0, 0, NOW(), NOW(), 1),
(NULL, NULL, 2, 'Boton de Alerta', 'boton de alerta en etiqueta form', 'JavaScript', '<!DOCTYPE html>\r\n<html>\r\n    <head>\r\n        <title>Titulo de la pagina..</title>\r\n        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>\r\n    </head>\r\n    <body>\r\n        <FORM>\r\n            <input name="button2" type="button" onclick=''alert("CUIDADO")'' value="Click Aqui para ver el ALERTA" />\r\n        </FORM>\r\n    </body>\r\n</html>', 0, 0, 0, 0, NOW(), NOW(), 1),
(NULL, NULL, 2, 'Reloj', 'reloj', 'JavaScript', '<!DOCTYPE html>\r\n<html>\r\n    <head>\r\n        <title>Titulo de la pagina..</title>\r\n        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>\r\n    </head>\r\n    <body>\r\n        <form name="Tick">\r\n            <input type="text" size="11" name="Clock" />\r\n        </form>\r\n        <script>\r\n            //CODIGO MEJORADO!!\r\n            function show(){\r\n                var Digital=new Date();\r\n                var hours=Digital.getHours();\r\n                var minutes=Digital.getMinutes();\r\n                var seconds=Digital.getSeconds();\r\n                var dn="AM";\r\n                if (hours>12){\r\n                    dn="PM";\r\n                    hours=hours-12;\r\n                }\r\n                if (hours==0)\r\n                    hours=12;\r\n                if (minutes<=9)\r\n                    minutes="0"+minutes;\r\n                if (seconds<=9)\r\n                    seconds="0"+seconds;\r\n                document.Tick.Clock.value=hours+":"+minutes+":"+seconds+" "+dn;\r\n                setTimeout("show()",1000) \r\n           } \r\n           show();\r\n        </script>\r\n    </body>\r\n</html>', 0, 0, 0, 0, NOW(), NOW(), 1),
(NULL, NULL, 2, 'Meses en Javascript', 'Imprime los 12 meses del año, usando for.', 'JavaScript', '<!DOCTYPE html>\r\n<html>\r\n    <head>\r\n        <title>Meses en JS</title>\r\n        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>\r\n    </head>\r\n    <body>\r\n        <script type="text/javascript">\r\n        // Array que almacena los 12 meses del anio\r\n        var meses=[ "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", \r\n                    "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre"];\r\n        for(var i=0;i<12;i++){\r\n            alert(meses[i]);    \r\n        }                    \r\n        </script>\r\n        <p>Esta pagina muestra los 12 meses del año</p>        \r\n    </body>\r\n</html>', 0, 0, 0, 0, NOW(), NOW(), 1),
(NULL, NULL, 3, 'Prueba de operadores logicos', 'Programa de prueba de operadores logicos en javascript', 'JavaScript', '<!DOCTYPE html>\r\n<html>\r\n    <head>\r\n        <title>Titulo de la pagina..</title>\r\n        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>\r\n    </head>\r\n    <body>\r\n        <script type="text/javascript">\r\n        var valores = [true, 5, false, "hola", "adios", 2];\r\n         \r\n        // Cual de los 2 elementos de texto es mayor\r\n        // Si el resultado es true, el primer texto es mayor\r\n        var resultado = valores[3] > valores[4];\r\n        alert(resultado);\r\n         \r\n        // Combinar valores booleanos\r\n        var valor1 = valores[0];\r\n        var valor2 = valores[2];\r\n         \r\n        // Obtener un resultado TRUE\r\n        var resultado = valor1 || valor2;\r\n        alert(resultado);\r\n         \r\n        // Obtener un resultado FALSE\r\n        resultado = valor1 && valor2;\r\n        alert(resultado);\r\n         \r\n        // Operaciones matemA¡ticas\r\n        var num1 = valores[1];\r\n        var num2 = valores[5];\r\n         \r\n        var suma = num1 + num2;\r\n        alert(suma);\r\n         \r\n        var resta = num1 - num2;\r\n        alert(resta);\r\n         \r\n        var multiplicacion = num1 * num2;\r\n        alert(multiplicacion);\r\n         \r\n        var division = num1 / num2;\r\n        alert(division);\r\n         \r\n        var modulo = num1 % num2;\r\n        alert(modulo);\r\n         \r\n        </script>\r\n        <p>Esta pagina muestra el uso basico de los operadores</p>\r\n    </body>\r\n</html>', 0, 0, 0, 0, NOW(), NOW(), 1),
(NULL, NULL, 3, 'Estructuras de control, IF', 'Programa de muestra para aprender a usar la sentecia IF', 'JavaScript', '<!DOCTYPE html>\r\n<html>\r\n    <head>\r\n        <title>Titulo de la pagina..</title>\r\n        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>\r\n    </head>\r\n    <body>\r\n        <script type="text/javascript">\r\n            var numero1 = 5;\r\n            var numero2 = 8;\r\n         \r\n            if(numero1 <= numero2) {\r\n                alert("numero1 no es mayor que numero2");\r\n            }\r\n            if(numero2 >= 0) {\r\n                alert("numero2 es positivo");\r\n            }\r\n            if(numero1 < 0 || numero1 != 0) {\r\n                alert("numero1 es negativo o distinto de cero");\r\n            }\r\n            if(++numero1 < numero2) {\r\n                alert("Incrementar en 1 unidad el valor de numero1 no lo hace mayor o igual que numero2");\r\n            }\r\n        </script>\r\n    </body>\r\n</html>', 0, 0, 0, 0, NOW(), NOW(), 1),
(NULL, NULL, 3, 'Calculo de DNI', 'Algoritmo para el calculo de DNI', 'JavaScript', '<!DOCTYPE html>\r\n<html>\r\n    <head>\r\n        <title>Calculo de DNI</title>\r\n        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>\r\n    </head>\r\n    <body>\r\n        <script type="text/javascript">\r\n            var letras = [''T'', ''R'', ''W'', ''A'', ''G'', ''M'', ''Y'', ''F'', ''P'', ''D'', ''X'', ''B'', ''N'', ''J'', ''Z'', ''S'', ''Q'', ''V'', ''H'', ''L'', ''C'', ''K'', ''E'', ''T''];\r\n         \r\n            var numero = prompt("Introduce tu numero de DNI (sin la letra)");\r\n            var letra = prompt("Introduce la letra de tu DNI (en mayusculas)");\r\n            letra = letra.toUpperCase();\r\n         \r\n            if(numero < 0 || numero > 99999999) {\r\n                alert("El numero proporcionado no es valido");\r\n            }\r\n            else {\r\n                var letraCalculada = letras[numero % 23];\r\n                if(letraCalculada != letra) {\r\n                    alert("La letra o el numero proporcionados no son correctos");\r\n                }\r\n                else {\r\n                    alert("El numero de DNI y su letra son correctos");\r\n                }\r\n            }\r\n        </script>\r\n        <p>Esta pA¡gina calcula la letra del DNI</p>\r\n    </body>\r\n</html>', 0, 0, 0, 0, NOW(), NOW(), 1),
(NULL, NULL, 3, 'Factorial de un numero', 'Calcula factorial de un numero', 'JavaScript', '<!DOCTYPE html>\r\n<html>\r\n    <head>\r\n        <title>Factorial de un numero</title>\r\n        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>\r\n    </head>\r\n    <body>\r\n        <script type="text/javascript">\r\n            var numero = prompt("Introduce un numero y se mostrara su factorial");\r\n            var resultado = 1;\r\n         \r\n            for(var i=1; i<=numero; i++) {\r\n                resultado *= i;\r\n            }\r\n            alert(resultado);\r\n        </script>\r\n    </body>\r\n</html>', 0, 0, 0, 0, NOW(), NOW(), 1),
(NULL, NULL, 3, 'Demostracion de funcion basica', 'Programa que determina si un numero es par o impar mediante funcion', 'JavaScript', '<!DOCTYPE html>\r\n<html>\r\n    <head>\r\n        <title>Funciones bA¡sicas</title>\r\n        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>\r\n    </head>\r\n    <body>\r\n        <script type="text/javascript">\r\n        var numero = prompt("Introduce un numero entero");\r\n         \r\n        var resultado = parImpar(numero);\r\n        alert("El numero "+numero+" es "+resultado);\r\n         \r\n        function parImpar(numero) {\r\n          if(numero % 2 == 0) {\r\n            return "par";\r\n          }\r\n          else {\r\n            return "impar";\r\n          }\r\n        }\r\n        </script>\r\n    </body>\r\n</html>', 0, 0, 0, 0, NOW(), NOW(), 1),
(NULL, NULL, 4, 'Informacion sobre cadenas', 'Determina si una cadena esta en mayuscula o minuscula', 'JavaScript', '<!DOCTYPE html>\r\n<html>\r\n    <head>\r\n        <title>Informacion sobre cadenas</title>\r\n        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>\r\n    </head>\r\n    <body>\r\n        <script type="text/javascript">\r\n            function info(cadena) {\r\n             \r\n              var resultado = "La cadena \\""+cadena+"\\" ";\r\n             \r\n              // Comprobar mayAºsculas y minAºsculas\r\n              if(cadena == cadena.toUpperCase()) {\r\n                resultado += " esta formada por mayusculas";\r\n              }\r\n              else if(cadena == cadena.toLowerCase()) {\r\n                resultado += " esta formada por minusculas";\r\n              }\r\n              else {\r\n                resultado += " esta formada por mayusculas y minusculas";\r\n              }\r\n             \r\n              return resultado;\r\n            }\r\n             \r\n            alert(info("OVNI = OBJETO VOLADOR NO IDENTIFICADO"));\r\n            alert(info("En un lugar de la mancha..."));\r\n        </script>\r\n    </body>\r\n</html>', 0, 0, 0, 0, NOW(), NOW(), 1),
(NULL, NULL, 4, 'Hola mundo', 'ocio', 'JavaScript', '<!DOCTYPE html>\r\n<html>\r\n<head>\r\n	<meta charset="utf-8">\r\n	<link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css">\r\n	<link rel="stylesheet" href="css/main.css">\r\n	<link href=''http://fonts.googleapis.com/css?family=Gloria+Hallelujah'' rel=''stylesheet'' type=''text/css''>\r\n	<link href=''http://fonts.googleapis.com/css?family=Lato:300,400,700'' rel=''stylesheet'' type=''text/css''>\r\n	<title>soullessdead</title>\r\n</head>\r\n<body>\r\n	<div class="col-md-4 center-block quitar-float text-center espacio-arriba">\r\n		<a href="index.html"><img src="img/Fiddlesticks_Splash_4.jpg"></a>\r\n	    <h1 class="gloria grande vinotinto">Fiddlestick</h1>\r\n	    <h2>Creo que te dejare sufrir un rato</h2>\r\n	    <nav>\r\n		    <a href="index.html" class="espacio-derecha">Fiddlesticks</a>\r\n		    <a href="menu.html" class="espacio-derecha">Skins</a>\r\n		    <a href="" class="espacio-derecha">Historia</a>\r\n		    <a href="" class="espacio-derecha">Splash Art</a>\r\n		</nav>\r\n	</div>\r\n</html>', 0, 0, 0, 0, NOW(), NOW(), 1),
(NULL, NULL, 4, 'Suma de numero pares e impares.', 'Programa que realiza suma desde el 1 al 100 y los muestra simultaneamente.', 'JavaScript', '<!DOCTYPE html>\r\n<html>\r\n    <head>\r\n        <title>Titulo de la pagina..</title>\r\n        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>\r\n    </head>\r\n    <body>\r\n        <script type="text/javascript">\r\n            var sumaPar=0;\r\n            var sumaImpar=0;\r\n            \r\n            for(var i=1;i<=200;i++){\r\n                if(i%2==0){\r\n                    sumaPar=sumaPar+i;\r\n                }else{\r\n                    sumaImpar=sumaImpar+i;\r\n                }\r\n                \r\n            }\r\n            alert("Suma par: " + sumaPar +"\\n Suma impar: " + sumaImpar);\r\n        </script>\r\n    </body>\r\n</html>', 0, 0, 0, 0, NOW(), NOW(), 1),
(NULL, NULL, 4, 'Tabla de multiplicar', 'Calcula e imprime tabla de multiplicar con ciclo for en javascript', 'JavaScript', '<!DOCTYPE html>\r\n<html>\r\n    <head>\r\n        <title>Tabla de multiplicar</title>\r\n        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>\r\n    </head>\r\n    <body>\r\n        <script type="text/javascript">\r\n            for(var i=1;i<=10;i++){\r\n                for(var j=1;j<=10;j++){\r\n                    document.write(i+"x"+j+"="+(i*j)+"<br>");\r\n                }\r\n                document.write("<br>");\r\n            }\r\n        </script>\r\n    </body>\r\n</html>', 0, 0, 0, 0, NOW(), NOW(), 1),
(NULL, NULL, 4, 'Identifica cadena en mayuscula y minuscula', 'Identifica cadena en mayuscula y minuscula', 'JavaScript', '<!DOCTYPE html>\r\n<html>\r\n    <head>\r\n        <title>Titulo de la pagina..</title>\r\n        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>\r\n    </head>\r\n    <body>\r\n        <script type="text/javascript">\r\n        //ADMIN: ASIGNAR UN TITULO A LA PAGINA PARA IDENTIFICARLA\r\n        function info(cadena) {\r\n          var resultado = "La cadena \\""+cadena+"\\" ";\r\n         \r\n          // Comprobar mayAºsculas y minAºsculas\r\n          if(cadena == cadena.toUpperCase()) {\r\n            resultado += " esta formada solo por mayusculas";\r\n          }\r\n          else if(cadena == cadena.toLowerCase()) {\r\n            resultado += " esta formada por minusculas";\r\n          }\r\n          else {\r\n            resultado += " esta formada por mayusculas y minusculas";\r\n          }\r\n         \r\n          return resultado;\r\n        }\r\n         \r\n        alert(info("OVNI = OBJETO VOLADOR NO IDENTIFICADO"));\r\n        alert(info("prueda del repositorio"));\r\n        alert(info("En un lugar de la mancha..."));\r\n        </script>\r\n    </body>\r\n</html>', 0, 0, 0, 0, NOW(), NOW(), 1),
(NULL, NULL, 5, 'Limitar numero de caracteres en textarea en Javascript', 'Programa que limita la cantidad de caracteres en textarea', 'JavaScript', '<!DOCTYPE html>\r\n<html>\r\n    <head>\r\n        <title>Limitar numero de caracteres en textarea</title>\r\n        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>\r\n    </head>\r\n    <body>\r\n        <script type="text/javascript">\r\n            function limita(elEvento, maximoCaracteres) {\r\n              var elemento = document.getElementById("texto");\r\n             \r\n              // Obtener la tecla pulsada \r\n              var evento = elEvento || window.event;\r\n              var codigoCaracter = evento.charCode || evento.keyCode;\r\n              // Permitir utilizar las teclas con flecha horizontal\r\n              if(codigoCaracter == 37 || codigoCaracter == 39) {\r\n                return true;\r\n              }\r\n             \r\n              // Permitir borrar con la tecla Backspace y con la tecla Supr.\r\n              if(codigoCaracter == 8 || codigoCaracter == 46) {\r\n                return true;\r\n              }\r\n              else if(elemento.value.length >= maximoCaracteres ) {\r\n                return false;\r\n              }\r\n              else {\r\n                return true;\r\n              }\r\n            }\r\n             \r\n            function actualizaInfo(maximoCaracteres) {\r\n              var elemento = document.getElementById("texto");\r\n              var info = document.getElementById("info");\r\n             \r\n              if(elemento.value.length >= maximoCaracteres ) {\r\n                info.innerHTML = "Maximo "+maximoCaracteres+" caracteres";\r\n              }\r\n              else {\r\n                info.innerHTML = "Puedes escribir hasta "+(maximoCaracteres-elemento.value.length)+" caracteres adicionales";\r\n              }\r\n            }\r\n        </script>\r\n        \r\n        <div id="info">Maximo 100 caracteres</div>\r\n        <textarea id="texto" onkeypress="return limita(event, 100);" onkeyup="actualizaInfo(100)" rows="6" cols="30"></textarea>\r\n    </body>\r\n</html>', 0, 0, 0, 0, NOW(), NOW(), 1),
(NULL, NULL, 5, 'Conocer los datos del navegador', 'datos del navegador usando Javascript', 'JavaScript', '<!DOCTYPE html>\r\n<html>\r\n    <head>\r\n        <title>Conocer los datos del navegador</title>\r\n        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>\r\n    </head>\r\n    <body>\r\n        <script type="text/javascript">\r\n            document.write("<p>Navegador: ");\r\n            document.write(navigator.appName + "</p>");\r\n            \r\n            document.write("<p>Version del navegador: ");\r\n            document.write(navigator.appVersion + "</p>");\r\n            \r\n            document.write("<p>Codigo: ");\r\n            document.write(navigator.appCodeName + "</p>");\r\n            \r\n            document.write("<p>Plataforma: ");\r\n            document.write(navigator.platform + "</p>");\r\n\r\n            document.write("<p>Cookies habilitadas: ");\r\n            document.write(navigator.cookieEnabled + "</p>");\r\n            \r\n            document.write("<p>Cabecera de agente de usuario del navegador: ");\r\n            document.write(navigator.userAgent + "</p>");            \r\n        </script>\r\n    </body>\r\n</html>', 0, 0, 0, 0, NOW(), NOW(), 1),
(NULL, NULL, 5, 'Saber cual es la resolucion de pantalla', 'Conocer los datos relacionados con la pantalla', 'JavaScript', '<!DOCTYPE html>\r\n<html>\r\n    <head>\r\n        <title>Titulo de la pagina..</title>\r\n        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>\r\n    </head>\r\n    <body>\r\n        <script type="text/javascript">\r\n            document.write("Resolucion de pantalla: ");\r\n            document.write(screen.width + "*" + screen.height);\r\n            document.write("<br>");\r\n            \r\n            document.write("Area visible disponible: ");\r\n            document.write(screen.availWidth + "*" + screen.availHeight);\r\n            document.write("<br>");\r\n            \r\n            document.write("Resolucion de color: ");\r\n            document.write(screen.colorDepth);\r\n            document.write(" bits<br>");\r\n        </script>\r\n    </body>\r\n</html>', 0, 0, 0, 0, NOW(), NOW(), 1),
(NULL, NULL, 5, 'coordenas-raton', 'Saber las cordenadas del rato en javascript', 'JavaScript', '<!DOCTYPE html>\r\n<html>\r\n    <head>\r\n        <title>Titulo de la pagina..</title>\r\n        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>\r\n    </head>\r\n    <body>\r\n        <form name="Show">\r\n        X <input type="text" name="MouseX" value="0" size="4"><br>\r\n        Y <input type="text" name="MouseY" value="0" size="4"><br>\r\n        </form>\r\n        \r\n        <script language="javascript">\r\n        <!-- Original:  CodeLifter.com (support@codelifter.com) -->\r\n        <!-- Web Site:  http://www.codelifter.com -->\r\n        \r\n        <!-- This script and many more are available free online at -->\r\n        <!-- The JavaScript Source!! http://javascript.internet.com -->\r\n        \r\n        <!-- Begin\r\n        var IE = document.all?true:false;\r\n        if (!IE) document.captureEvents(Event.MOUSEMOVE)\r\n        document.onmousemove = getMouseXY;\r\n        var tempX = 0;\r\n        var tempY = 0;\r\n        function getMouseXY(e) {\r\n        if (IE) { // grab the x-y pos.s if browser is IE\r\n        tempX = event.clientX + document.body.scrollLeft;\r\n        tempY = event.clientY + document.body.scrollTop;\r\n        }\r\n        else {  // grab the x-y pos.s if browser is NS\r\n        tempX = e.pageX;\r\n        tempY = e.pageY;\r\n        }  \r\n        if (tempX < 0){tempX = 0;}\r\n        if (tempY < 0){tempY = 0;}  \r\n        document.Show.MouseX.value = tempX;\r\n        document.Show.MouseY.value = tempY;\r\n        return true;\r\n        }\r\n        //  End -->\r\n        </script>\r\n    </body>\r\n</html>', 0, 0, 0, 0, NOW(), NOW(), 1);

-- eventos
DROP TABLE IF EXISTS `evento`;
CREATE TABLE IF NOT EXISTS `evento` (
	`ideve` int(11) AUTO_INCREMENT NOT NULL COMMENT 'Identificador de evento.',
	`idusu` int(11) NOT NULL COMMENT '',
	`idcod` int(11) NOT NULL COMMENT 'Identificador de codigo fuente.',	
	`idcodori` int(11) NULL COMMENT 'Identificador de codigo fuente padre.',
	`accion` varchar(10) NOT NULL COMMENT '',
	`fecha_registro` datetime NOT NULL COMMENT 'Fecha de creacion del registro.',
	`fecha_edicion` datetime NOT NULL COMMENT 'Fecha de ultima edicion del registro.',
	`estado_registro` int(1) NOT NULL COMMENT 'Codigo del estado del registro.',
	PRIMARY KEY (`ideve`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

INSERT INTO `evento` (`ideve`, `idusu`, `idcod`, `idcodori`, `accion`, `fecha_registro`, `fecha_edicion`, `estado_registro`) VALUES
(NULL, 1, 1, NULL, 'NUEVO', NOW(), NOW(), 1),
(NULL, 1, 2, 1, 'MEJORA', NOW(), NOW(), 1),
(NULL, 1, 3, NULL, 'NUEVO', NOW(), NOW(), 1),
(NULL, 1, 4, NULL, 'NUEVO', NOW(), NOW(), 1),
(NULL, 1, 5, NULL, 'NUEVO', NOW(), NOW(), 1),
(NULL, 1, 6, NULL, 'NUEVO', NOW(), NOW(), 1),
(NULL, 1, 7, NULL, 'NUEVO', NOW(), NOW(), 1),
(NULL, 1, 8, NULL, 'NUEVO', NOW(), NOW(), 1),
(NULL, 1, 9, NULL, 'NUEVO', NOW(), NOW(), 1),
(NULL, 1, 10, NULL, 'NUEVO', NOW(), NOW(), 1),
(NULL, 1, 11, NULL, 'NUEVO', NOW(), NOW(), 1),
(NULL, 1, 12, NULL, 'NUEVO', NOW(), NOW(), 1),
(NULL, 1, 13, NULL, 'NUEVO', NOW(), NOW(), 1),
(NULL, 1, 14, NULL, 'NUEVO', NOW(), NOW(), 1),
(NULL, 1, 15, NULL, 'NUEVO', NOW(), NOW(), 1),
(NULL, 1, 16, NULL, 'NUEVO', NOW(), NOW(), 1),
(NULL, 1, 17, NULL, 'NUEVO', NOW(), NOW(), 1),
(NULL, 1, 18, NULL, 'NUEVO', NOW(), NOW(), 1),
(NULL, 1, 19, NULL, 'NUEVO', NOW(), NOW(), 1),
(NULL, 1, 20, NULL, 'NUEVO', NOW(), NOW(), 1),
(NULL, 1, 21, NULL, 'NUEVO', NOW(), NOW(), 1),
(NULL, 1, 22, NULL, 'NUEVO', NOW(), NOW(), 1),
(NULL, 1, 23, NULL, 'NUEVO', NOW(), NOW(), 1),
(NULL, 1, 24, NULL, 'NUEVO', NOW(), NOW(), 1),
(NULL, 1, 25, NULL, 'NUEVO', NOW(), NOW(), 1),
(NULL, 1, 26, NULL, 'NUEVO', NOW(), NOW(), 1),
(NULL, 1, 27, NULL, 'NUEVO', NOW(), NOW(), 1),
(NULL, 1, 28, NULL, 'NUEVO', NOW(), NOW(), 1),
(NULL, 1, 29, 28, 'MEJORA', NOW(), NOW(), 1),
(NULL, 1, 30, NULL, 'NUEVO', NOW(), NOW(), 1),
(NULL, 1, 31, NULL, 'NUEVO', NOW(), NOW(), 1),
(NULL, 1, 32, NULL, 'NUEVO', NOW(), NOW(), 1),
(NULL, 1, 33, NULL, 'NUEVO', NOW(), NOW(), 1);

--
-- DELETE FROM `codigo` WHERE idcod > 8;
-- TRUNCATE TABLE `codigo`;
TRUNCATE TABLE `evento`;